[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd packages/backend && npm run build && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "5000"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "true"
NPM_CONFIG_TIMEOUT = "600000"
NPM_CONFIG_FETCH_TIMEOUT = "600000"
