[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd packages/backend-lite && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000"
